ENH: update circleci config for docker run testing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,59 +1,305 @@
-
 version: 2
 jobs:
   build:
+    environment:
+      TZ: "/usr/share/zoneinfo/Europe/Zurich"
+      SCRATCH: "/scratch"
     docker:
-      - image: circleci/python:2.7
-    working_directory: ~/multiscalebrainparcellator
+      - image: docker:18.01.0-ce-git
+    working_directory: tmp/src/multiscalebrainparcellator
     steps:
+      - run:
+          name: Install parallel gzip
+          command: |
+            apk add --no-cache pigz python2.7
+      - restore_cache:
+          keys:
+            - docker-{{ .Branch }}-{{ epoch }}
+            - docker-{{ .Branch }}-
+            - docker-master-
+            - docker-
+          paths:
+            - /tmp/cache/docker.tar.gz
       - checkout
-      # - run:
-      #     name: verify git tag vs. version
-      #     command: |
-      #       python -m venv venv
-      #       . venv/bin/activate
-      #       python setup.py verify
-      # - run:
-      #     name: init .pypirc
-      #     command: |
-      #       echo -e "[pypi]" >> ~/.pypirc
-      #       echo -e "username = madhurt" >> ~/.pypirc
-      #       echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
-      # - run:
-      #     name: create packages
-      #     command: |
-      #       python3 setup.py sdist
-      #       python3 setup.py bdist_wheel
-      # - run:
-      #     name: upload to pypi
-      #     command: |
-      #       . venv/bin/activate
-      #       twine upload dist/*
       - setup_remote_docker:
           docker_layer_caching: true
+      - run:
+          name: Load Docker image layer cache
+          no_output_timeout: 30m
+          command: |
+            docker info
+            set +o pipefail
+            if [ -f /tmp/cache/docker.tar.gz ]; then
+              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
+              docker images
+            fi
+      - run:
+          name: Build Docker image
+          no_output_timeout: 60m
+          command: |
+            # Get version, update files.
+            THISVERSION=$( python get_version.py )
+            if [[ ${THISVERSION:0:1} == "0" ]] ; then
+              echo "WARNING: latest git tag could not be found"
+              echo "Please, make sure you fetch all tags from upstream with"
+              echo "the command ``git fetch --tags --verbose`` and push"
+              echo "them to your fork with ``git push origin --tags``"
+            fi
+            # Build docker image
+            e=1 && for i in {1..5}; do
+              docker build \
+                --cache-from=sebastientourbier/multiscalebrainparcellator \
+                --rm=false \
+                -t sebastientourbier/multiscalebrainparcellator:latest \
+                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
+                --build-arg VCS_REF=`git rev-parse --short HEAD` \
+                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
+              && e=0 && break || sleep 15
+            done && [ "$e" -eq "0" ]
+      - run:
+          name: Docker save
+          no_output_timeout: 40m
+          command: |
+            mkdir -p /tmp/cache
+            docker save ubuntu:16.04 sebastientourbier/multiscalebrainparcellator-ubuntu16.04:latest sebastientourbier/multiscalebrainparcellator:latest \
+            | pigz -8 -p 3 > /tmp/cache/docker.tar.gz
+      - persist_to_workspace:
+          root: /tmp
+          paths:
+            - cache/docker.tar.gz
+            - src/multiscalebrainparcellator
 
+  get_data:
+    machine:
+      # Ubuntu 14.04 with Docker 17.10.0-ce
+      image: circleci/classic:201711-01
+    working_directory: /home/circleci/data
+    steps:
+      - restore_cache:
+          keys:
+            - data-{{ epoch }}
+            - data-
       - run:
-          name: Install Docker client
+          name: Get test data from ds000005
           command: |
-            set -x
-            VER="17.03.0-ce"
-            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
-            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
-            sudo mv /tmp/docker/* /usr/bin
+            mkdir -p /tmp/data
+            if [[ ! -d /tmp/data/ds005 ]]; then
+              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
+                -O ds005_downsampled.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/57f32a429ad5a101f977eb75"
+              tar xvzf ds005_downsampled.tar.gz -C /tmp/data/
+            else
+              echo "Dataset ds000005 was cached"
+            fi
       - run:
-          name: Build and push Docker image
+          name: Get FreeSurfer derivatives for ds000005
           command: |
-            docker login -u $DOCKER_USER -p $DOCKER_PASS
-            docker build -t sebastientourbier/multiscalebrainparcellator:circleci .
-            docker push sebastientourbier/multiscalebrainparcellator:circleci
+            if [[ ! -d /tmp/ds005/derivatives/freesurfer ]]; then
+              mkdir -p /tmp/ds005/derivatives
+              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
+                -O ds005_derivatives_freesurfer.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/58fe59eb594d900250960180"
+              tar xvzf ds005_derivatives_freesurfer.tar.gz -C /tmp/ds005/derivatives
+            else
+              echo "FreeSurfer derivatives of ds000005 were cached"
+            fi
+      - run:
+          name: Store FreeSurfer license file
+          command: |
+            mkdir -p /tmp/fslicense
+            cd /tmp/fslicense
+            echo "c2ViYXN0aWVuLnRvdXJiaWVyMUBnbWFpbC5jb20KMzAwNzYKICpDYUpVZ0VMQlJEYkEKIEZTMkkyWDNwNkpicWcK==" | base64 -d > /tmp/fslicense/license.txt
+      - persist_to_workspace:
+          root: /tmp
+          paths:
+            - data
+            - fslicense
+            - ds005/derivatives
+      - save_cache:
+         key: data-{{ epoch }}
+         paths:
+            - /tmp/data
+            - /tmp/ds005/derivatives/freesurfer
+
+  update_cache:
+    machine:
+      # Ubuntu 14.04 with Docker 17.10.0-ce
+      image: circleci/classic:201711-01
+    working_directory: /tmp/src/multiscalebrainparcellator
+    steps:
+      - attach_workspace:
+          at: /tmp
+      - save_cache:
+         key: docker-{{ .Branch }}-{{ epoch }}
+         paths:
+           - /tmp/cache/docker.tar.gz
+
+  ds005:
+    machine:
+      image: circleci/classic:201711-01
+    working_directory: /tmp/ds005
+    environment:
+      - FS_LICENSE: /tmp/fslicense/license.txt
+    steps:
+      - checkout:
+          path: /home/circleci/src/multiscalebrainparcellator
+      - run:
+          name: Check whether build should be skipped
+          command: |
+            cd /home/circleci/src/fmriprep
+            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?ds005\]' )" != "" ]]; then
+              echo "Skipping ds000005 build"
+              circleci step halt
+            fi
+      - attach_workspace:
+          at: /tmp
+      - restore_cache:
+          keys:
+            - ds005-anat-v12-{{ .Branch }}-{{ epoch }}
+            - ds005-anat-v12-{{ .Branch }}
+            - ds005-anat-v12-master
+            - ds005-anat-v12-
+      - run:
+          name: Load Docker image layer cache
+          no_output_timeout: 30m
+          command: |
+            docker info
+            set +o pipefail
+            if [ -f /tmp/cache/docker.tar.gz ]; then
+              sudo apt update && sudo apt -y install pigz
+              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
+              docker images
+            fi
+      - run:
+          name: Run anatomical workflow on ds005
+          no_output_timeout: 2h
+          command: |
+            mkdir -p /tmp/ds005/work /tmp/ds005/derivatives
+            sudo setfacl -d -m group:$(id -gn):rwx /tmp/ds005/derivatives && \
+                sudo setfacl -m group:$(id -gn):rwx /tmp/ds005/derivatives
+            sudo setfacl -d -m group:$(id -gn):rwx /tmp/ds005/work && \
+                sudo setfacl -m group:$(id -gn):rwx /tmp/ds005/work
+            docker run -it --rm \
+                -v /tmp/data/ds005:/bids_dataset \
+                -v /tmp/data/ds005/derivatives:/bids_dataset/derivatives \
+                -v $FS_LICENSE:/opt/freesurfer/license.txt \
+                -u $(id -u):$(id -g) \
+                sebastientourbier/multiscalebrainparcellator:latest \
+                /bids_dataset /bids_dataset/derivatives participant --participant_label 01 \
+                --isotropic_resolution 1.0 \
+                --thalamic_nuclei \
+                --hippocampal_subfields \
+                --brainstem_structures
+
+      - save_cache:
+         key: ds005-anat-v12-{{ .Branch }}-{{ epoch }}
+         paths:
+            - /tmp/ds005/work
+            - /tmp/ds005/derivatives/cmp
+      - run:
+          name: Checking outputs of MultiScaleBrainParcellator run
+          command: |
+            mkdir -p /tmp/ds005/test
+            find /tmp/ds005/derivatives -path */figures -prune -o -name "*" -print | sed s+/tmp/ds005/derivatives/++ | sort > /tmp/ds005/test/outputs.out
+            diff /tmp/src/multiscalebrainparcellator/.circleci/ds005_outputs.txt /tmp/ds005/test/outputs.out
+            exit $?
+      - run:
+          name: Clean working directory
+          when: always
+          command: |
+            sudo chown $(id -un):$(id -gn) -R /tmp/ds005
+            find /tmp/ds005/work -not -name "*.svg" -not -name "*.html" -not -name "*.rst" \
+                -not -name "*.mat" -not -name "*.gpickle" -not -name "*.lta" -not -name "*.json" -not -name "*.txt" -not -name "*.pklz" -type f -delete
+      - store_artifacts:
+        path: /tmp/ds005
+
+  deploy_docker:
+    machine:
+      # Ubuntu 14.04 with Docker 17.10.0-ce
+      image: circleci/classic:201711-01
+    working_directory: /tmp/src/multiscalebrainparcellator
+    steps:
+      - attach_workspace:
+          at: /tmp
+      - run:
+          name: Load Docker image layer cache
+          no_output_timeout: 30m
+          command: |
+            docker info
+            set +o pipefail
+            if [ -f /tmp/cache/docker.tar.gz ]; then
+              sudo apt update && sudo apt -y install pigz
+              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
+              docker images
+            fi
+      - run:
+          name: Deploy to Docker Hub
+          no_output_timeout: 40m
+          command: |
+            if [[ -n "$DOCKER_PASS" ]]; then
+              docker login -u $DOCKER_USER -p $DOCKER_PASS
+              docker tag sebastientourbier/multiscalebrainparcellator sebastientourbier/multiscalebrainparcellator:unstable
+              docker push sebastientourbier/multiscalebrainparcellator:unstable
+              if [[ -n "$CIRCLE_TAG" ]]; then
+                docker push sebastientourbier/multiscalebrainparcellator:latest
+                docker tag sebastientourbier/multiscalebrainparcellator sebastientourbier/multiscalebrainparcellator:$CIRCLE_TAG
+                docker push sebastientourbier/multiscalebrainparcellator:$CIRCLE_TAG
+              fi
+            fi
+
 workflows:
   version: 2
-  build_and_deploy:
+  build_test_deploy:
     jobs:
       - build:
           filters:
             tags:
-              only: /[0-9]+(\.[0-9]+)*/
+              only: /.*/
+
+      - get_data:
+          filters:
             branches:
-              only:
-                -master
+              ignore:
+                - /docs?\/.*/
+            tags:
+              only: /.*/
+
+      # - build_docs:
+      #     requires:
+      #       - build
+      #     filters:
+      #       branches:
+      #         ignore:
+      #           - /ds005\/.*/
+      #       tags:
+      #         only: /.*/
+
+      - update_cache:
+          requires:
+            - build
+          filters:
+            branches:
+              ignore:
+                - /docs?\/.*/
+            tags:
+              only: /.*/
+
+      - ds005:
+          requires:
+            - get_data
+            - build
+          filters:
+            branches:
+              ignore:
+                - /docs?\/.*/
+            tags:
+              only: /.*/
+
+      - deploy_docker:
+          requires:
+            - build
+            # - build_docs
+            - ds005
+          filters:
+            branches:
+              only: master
+            tags:
+              only: /^v.*/
